-- Reset passwords with correct BCrypt hashes generated by Java BCryptPasswordEncoder
-- admin: admin123
-- testuser: test123

UPDATE users SET password_hash = '$2a$10$TFj1hsfFNp6a2fp4yi1ln.HS6uwgL0IjsyMvCq99l5WJzIG9WbqVW', failed_attempts = 0, status = 'active', locked_until = NULL WHERE username = 'admin';

UPDATE users SET password_hash = '$2a$10$WIENlNplOixHHivlcfuJOOHysTkF.v8vUYuqtrgRXIm3ZhvxNuojW', failed_attempts = 0, status = 'active', locked_until = NULL WHERE username = 'testuser';
